master:
  host: master-node
  port: 12345

workers:
  - host: worker-node-1
    port: 12346
  - host: worker-node-2
    port: 12347

training:
  model: resnet50
  dataset: /path/to/dataset
  epochs: 10
  batch_size: 32